version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/src/main/frontend/'
    schedule:
      interval: 'daily'

  # Maintain dependencies for maven
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'daily'
